-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 24, 2017 at 12:18 PM
-- Server version: 5.5.54-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `aasha`
--

-- --------------------------------------------------------

--
-- Table structure for table `paper`
--

CREATE TABLE IF NOT EXISTS `paper` (
  `ID` int(11) NOT NULL,
  `title` varchar(500) DEFAULT NULL,
  `abstract` longtext,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `paper`
--

INSERT INTO `paper` (`ID`, `title`, `abstract`) VALUES
(5715225, 'Evolving Arbitrarily Connected Feedforward Neural Networks via Genetic Algorithms', 'Though several approaches have already been proposed in the literature to evolve neural network topologies for solving a wide range of machine learning tasks, this paper presents an alternative one, capable of evolving arbitrarily connected feed forward neural networks (ACFNNs), including linear and nonlinear neurons. A genetic algorithm is conceived to adjust the topology and also to perform variable selection. The weights of the obtained neural networks, with arbitrary topologies, are adjusted using a simple descent gradient algorithm. The purpose is to obtain high-quality and parsimonious predictors for two real-world and one synthetic time series. The obtained results are compared with the ones produced by traditional MLP models and Mixtures of Heterogeneous Experts (MHEs).'),
(5955202, 'Optimum memory color extraction for digital TVs based on genetic algorithm', 'Perceptual image quality is one of the most important performance indicators for digital TVs. In order to provide pleasing impression on viewers, preferred color correction that modifies memory colors is often applied. The first step of the preferred color correction is to extract pixels of memory colors. This paper presents a new method to determine the optimized boundary of geometrical figures for memory color extraction. Genetic algorithm is utilized for optimization. Based on relationship between lightness and hue and/or chroma, range of lightness is subdivided into three groups. Boundary of geometrical figure is determined for each group. Performance of the proposed method is evaluated by calculating the extraction accuracies. Experimental results indicate that proposed method outperforms previous methods proposed for the memory color extraction.'),
(6825032, 'Authentication in GPS-directed mobile clouds', 'Mobile clouds fuse cloud computing and mobile computing with wireless networking in everyday life. Many applications of mobile clouds deploy GPS (Global Positioning System) to find locations and to synchronize clocks. Though security starts to draw scrutiny from academy, industry, and government, authentication in GPS-directed mobile clouds has not been brought to the table. Authentication of GPS acts as the first responder against security breaches. This paper, among the first, examines the vulnerabilities in GPS-directed mobile clouds. By systematic analysis, an attack model is devised to demonstrate the existing threats and to predict futuristic attack tactics. The paper proposes a novel defense approach, namely vertical-horizontal design of authentication. Vertical-horizontal design extends cross-layer design of cloud and device stacks (vertical) with interface design between sections of the system (horizontal). The solutions will be validated with event-driven simulation that complements incidental dangers and legal/regulation restrictions associated in experimenting with GPS-dependent systems.'),
(7312541, 'Experimental testing of a random neural network smart controller using a single zone test chamber', 'Monitoring and analysis of energy use and indoor environmental conditions is an urgent need in large buildings to respond to changing conditions in an efficient manner. Correct estimation of occupancy will further improve energy performance. In this work, a smart controller for maintaining a comfortable environment using multiple random neural networks (RNNs) has been developed. The implementation of RNN-based controller is demonstrated to be more efficient on hardware and requires less memory compared to both artificial neural networks and model predictive controllers. This controller estimates the number of room occupants by using the information from wireless sensor nodes placed in the Heating, Ventilation and Air Conditioning (HVAC) duct and the room. For an occupied room, the controller can switch between thermal comfort mode (based on predicted mean vote set points) and user defined mode (i.e. occupant defined set points for heating/cooling/ventilation). Furthermore, the hybrid particle swarm optimisation with sequential quadratic programming training algorithms are used (for the first time to the best of the authors'' knowledge) for training the RNN and results show that this algorithm outperforms the widely used gradient descent algorithm for RNN. The results show that occupancy estimation by smart controller is 83.08% accurate.'),
(7358548, 'A review on availability of remote sensing data', 'The satellite images are applied on a wide range of applications. It plays a vital role in monitoring and maintaining the environmental changes and also in many agricultural applications. Nowadays, the Land degradation, Ground water scarcity and other climatic hazards are intensively high and it needs development of more advanced prediction models. These models can be deployed more effectively on using satellite images. Due to the launch of many modern satellites the availability of satellite images are high but still the exploitation of these resources are very scarce. It is due to the lack of knowledge over varied properties and the availability of different sources of satellite images. Though the moderate resolution satellite images are freely available, the rate of exploitation of these resources is still very less. Hence, this paper focuses on detailing the diverse characteristics and availability of satellite images which could be a great help for beginners in remote sensing research. In addition the details on major satellite derived products which are applied widely in different mapping applications are also listed. Further, the importance of satellite images in few notable applications is also explained.'),
(7375453, 'Microwave treatment of agricultural soil samples', 'Samples of agricultural soil, sown with Eruca sativa Mill. or Portulaca oleracea L., underwent to different microwave (MW) treatments in reverberating chamber (Incident Power = 600 W), varying in the exposure time. Brief treatment with MWs caused a decrease of P. oleracea seed germination up to 30-50 %, relative to controls, whilst seeds of E. sativa, underwent to the same MW treatments (Incident Power 100 W, T1 = 1 min, T2= 30 sec and T3 = 2 min), did not influence seed germination. However, the T2 MW treatment strongly inhibited seed germination. The MW exposition clearly influences germination of the assayed seeds, consequently this methodology might be particularly effective in weed and pest control of agricultural soils.'),
(7377291, 'Evaluation of Docker as Edge computing platform', 'High latency, network congestion and network bottleneck are some of problems in cloud computing. Moving from centralized to decentralized paradigm, Edge computing could offload the processing to the edge which indirectly reduces application response time and improves overall user experience. This paper evaluate Docker, a container based technology as a platform for Edge Computing. 4 fundamental criteria were evaluated 1) deployment and termination, 2) resource & service management, 3) fault tolerance and 4) caching. Based on our evaluation and experiment Docker provides fast deployment, small footprint and good performance which make it potentially a viable Edge Computing platform.'),
(7388330, 'A wireless sensor for food quality detection by UHF RFID passive tags', 'In this paper, we present a novel wireless sensor for the detection of food quality. The main idea is to integrate the sensing capability into UHF RFID tags thanks to the relation between physical read-range and permittivity of object in that we labeled RFID tags. From the knowledge in variation of food permittivity in function to time by experimental characterization, it is possible to detect the contamination time from which the food becomes improper for consumption based on the measurement of read-range with designed sensing tags. This low-cost UHF RFID passive sensor was designed and experimentally tested on beef with the same storage conditions in supermarket. The tendency agreement between experimental and simulation results show the potential of this technique for real-world applications in food traceability.'),
(7482764, 'Modeling Managed Grassland Biomass Estimation by Using Multitemporal Remote Sensing Data-A Machine Learning Approach', 'More than 80% of agricultural land in Ireland is grassland, which is a major feed source for the pasture based dairy farming and livestock industry. Many studies have been undertaken globally to estimate grassland biomass by using satellite remote sensing data, but rarely in systems like Ireland''s intensively managed, but small-scale pastures, where grass is grazed as well as harvested for winter fodder. Multiple linear regression (MLR), artificial neural network (ANN) and adaptive neuro-fuzzy inference system (ANFIS) models were developed to estimate the grassland biomass (kg dry matter/ha/day) of two intensively managed grassland farms in Ireland. For the first test site (Moorepark) 12 years (2001-2012) and for second test site (Grange) 6 years (2001-2005, 2007) of in situ measurements (weekly measured biomass) were used for model development. Five vegetation indices plus two raw spectral bands (RED=red band, NIR=Near Infrared band) derived from an 8-day MODIS product (MOD09Q1) were used as an input for all three models. Model evaluation shows that the ANFIS (R2Moorepark=0.85,RMSEMoorepark=11.07; R2Grange=0.76,RMSEGrange=15.35) has produced improved estimation of biomass as compared to the ANN and MLR. The proposed methodology will help to better explore the future inflow of remote sensing data from spaceborne sensors for the retrieval of different biophysical parameters, and with the launch of new members of satellite families (ALOS-2, Radarsat-2, Sentinel, TerraSAR-X, TanDEM-X/L) the development of tools to process large volumes of image data will become increasingly important.'),
(7574269, 'A Closed-Loop Reciprocity Calibration Method for Massive MIMO in Terrestrial Broadcasting Systems', 'Massive multi-input multioutput (MIMO) is believed to be an effective technique for future terrestrial broadcasting systems. Reciprocity calibration is one of the major practical challenges for massive MIMO systems operating in time-division duplexing mode. A new closed-loop reciprocity calibration method is investigated in this paper which can support online calibration with a higher accuracy compared to the existing methods. In the first part of the proposed method, an optimized relative calibration is introduced using the same structure of traditional relative calibration, but with less impaired hardware in the reference radio chain. In the second part, a test device (TD)-based calibration is proposed which makes online calibration possible. An experiment setup is built for the measurement of the base station hardware impairments and TD-based calibration implementation. Simulation results and the error vector magnitude of UE received signal after calibration show that the performance of our proposed method is improved significantly compared to the existing relative calibration methods.'),
(7730364, 'Soil Moisture data product generated from NASA SMAP observations with NOAA ancillary data', 'NASA Soil Moisture Active/Passive (SMAP) satellite was launched on January 31st, 2015 and has been providing level-1B radiometer brightness temperature (L1B-TB) data with an official latency of 12 hours since April 2015. The primary application users of the SMAP radiometer observations include numerical weather prediction operations that require shorter data latency (e.g. less than 6 hours). With slightly simplified algorithms of the L1B-TB data, NASA SMAP project is also providing near real time (NRT) L1B-TB data to NOAA operational users with a latency ranging from 2-6 hours. With this latency NOAA NWP models could use most of those SMAP half-orbit data that arrives within the 6 hour cut-off time limit. Before a radiance data assimilation capability for NOAA NWP models is developed, NOAA NESDIS is retrieving soil moisture from the NRT L1B-TB data through its Soil Moisture Product System (SMOPS) and makes surface soil moisture directly available for assimilation into the NWP models with the shortest possible turn-around time. Unlike using NASA GEOS model surface and soil temperature and multi-year average vegetation index data, SMOPS soil moisture retrieval algorithm uses the surface temperature data from operational Global Forecast System (GFS) and the vegetation index (NDVI) data from the near real time Suomi-NPP VIIRS observations. This paper introduce the structure of SMOPS, the soil moisture retrieval algorithm for SMAP data, and validation of the soil moisture data products against in the situ soil moisture measurements collected from the Soil Climate Analysis Networks of US Department of Agriculture and the Tibetan Soil Moisture Networks of Chinese Academy of Sciences. The soil moisture data retrieved from SMAP NRT TB data through SMOPS are also evaluated against the NASA official SMAP Level 2/3 soil moisture products. Preliminary validation results indicate that the SMAP soil moisture product from the SMAP NRT TB data and NESDIS SMOPS has similar quality to the NASA official products, but has shorter latency which may be critical to NOAA NWP operations.'),
(7730387, 'Benefit of modeling the observation error in a data assimilation framework using vegetation information obtained from passive-based microwave data', 'A primary operational goal of the United States Department of Agriculture (USDA) is to improve foreign market access for U.S. agricultural products. A large fraction of this crop condition assessment is based on satellite imagery and ground data analysis. The baseline soil moisture estimates that are currently used for this analysis are based on output from the modified Palmer two-layer soil moisture model, updated to assimilate near-real time observations derived from the Soil Moisture Ocean Salinity (SMOS) satellite. The current data assimilation system is based on a 1-D Ensemble Kalman Filter approach, where the observation error is modeled as a function of vegetation density. This allows for offsetting errors in the soil moisture retrievals. The observation error is currently adjusted using Normalized Difference Vegetation Index (NDVI) climatology. In this paper we explore the possibility of utilizing microwave-based vegetation optical depth instead.'),
(7768306, 'A comparison of radiative transfer models for predicting the microwave emission from soils', 'Two general types of numerical models for predicting microwave emission from soils are compared-coherent and noncoherent. In the former, radiation in the soil is treated coherently, and the boundary conditions on the electric fields across the layer boundaries are used to calculate the radiation intensity. In the latter, the radiation is assumed to be noncoherent, and the intensities of the radiation are considered directly. The results from the two approaches may be different because of the effects of interference, which can cause the transmitted intensity at the surface (i.e., emission) to be sometimes higher and sometimes lower for the coherent case than for the noncoherent case, depending on the relative phases of the reflected fields from the lower layers. This coupling between soil layers in the coherent models leads to greater soil moisture sampling depths observed with this type of model, and is the major difference that is found between the two types of models. In noncoherent models, the transmission at the surface is determined by the dielectric constant at the air/soil interface. The subsequent differences in the results are functions of both the frequency of the radiation being considered and the steepness of the moisture (i.e., dielectric constant) gradient near the surface. The calculations were performed at frequencies of 1.4 and 19.4 GHz and for two sets of soil profiles. Little difference was observed between the models at 19.4 GHz; and only at the lower frequency were differences apparent because of the greater soil moisture sampling depth at this frequency. For those situations which have a nonuniform temperature profile a definition for an effective emissivity is given, that is, the ratio of brightness temperature to the effective radiating temperature, the latter being a weighted average temperature over the emitting depth. Measurements from a tower are presented which show excellent agreement with the calculations from the coherent model.'),
(7814581, 'VP-Rec: A Hybrid Image Recommender Using Visual Perception Network', 'A requirement for a great user experience is to meet the exact needs for the usage of a recommender system. Such systems need user''s historical preferences to reasonably perform, which might not be the case for a cold-start user. This paper presents VP-Rec, a hybrid image recommender system that addresses the new user cold-start problem. VP-Rec combines user visual perception and pairwise preferences as source of information to perform recommendations. First, we infer pairwise preferences from users ratings. Next, we build visual perception networks linking users according to their visual attention similarities. From these two inferred structures, we build consensual prediction models, so that when a new user enters the system, we capture his visual attention and choose the best model that fits him. The system has been tested on two image datasets, getting important improvements in terms of ranking quality (nDCG) when applied to new user cold-start scenario against state-of-art recommender systems.'),
(7816636, 'Learning through Overcoming Inconsistencies', 'Of all the perspectives about what inconsistencies entail and how we can handle them, one that escapes our attention is that inconsistencies can serve as effective stimuli to learning because they often help reveal the inadequacies, gaps, deficiencies, or boundary conditions in an agent''s problem-solving knowledge. In this paper, we describe a new machine learning approach: inconsistency-induced learning where a learning episode is triggered by some inconsistent phenomenon and learning is essentially embodied in the process of finding ways to overcome such inconsistent phenomenon. Each learning episode causes an agent''s task-performing knowledge to be revised, refined, or augmented, which in turn incrementally improves its problem-solving performance. If such a learning agent can be engaged in an open-ended and alternating sequence of task-performing episodes and learning episodes, we can refer to it as a perpetual learning agent. We also provide an overview of related work in the paper.'),
(7828429, 'A Novel Method for Tuning Configuration Parameters of Spark Based on Machine Learning', 'Apache Spark is an open source distributed data processing platform, which can use distributed memory abstraction to process large volume of data efficiently. With the application of Apache Spark more and more widely, some problems are exposed. One of the most important aspects is the performance problem. Apache Spark has more than 180 configuration parameters, which can be adjusted by users according to their own specific application so as to optimize the performance. Currently these parameters are tuned manually by trial and error, which is ineffective due to the large parameter space and the complex interactions among the parameters. In this paper, in order to make the parameter tuning process of Spark more effective, a novel method for tuning configuration of Spark based on machine learning is proposed, which is composed of binary classification and multi-classification. This method can be used to auto-tune the configuration parameters of Spark. Furthermore, several common machine learning algorithms based on the proposed method are explored, and experimental results show that decision tree model (C5.0) is the best model considering the accuracy and computational efficiency. Finally, the experimental results also show that the performance can get average 36% gain with the proposed method compared with the default configuration of Spark.'),
(7839233, 'Eliminating Driving Distractions: Human-Computer Interaction with Built-In Applications', 'This article proposes a novel smart car demonstration platform, with a focus on the intuitive paradigm of human-computer interaction (HCI). The main objective here is to circumvent driver distraction when manipulating built-in car-appropriate applications (apps) for future smart car development. Two major development directions for a smart car''s HCI are investigated and discussed in detail: 1) an in-vehicle user interface, which focuses on utilizing the user interface of a transparent windshield display to keep the driver''s head up and eyes focused on the roadway, and 2) an in-vehicle interaction design, which emphasizes an intuitive interaction framework to minimize distractions while driving. This article addresses the major difficulties of each direction and discusses related challenges and solutions to achieve safety and comfort during smart car operation.'),
(7844785, 'Arabic sign language recognition system based on wavelet networks', 'Developing an automatic arabic sign language recognition system is of great importance, it can be used as a communication means between hearing-impaired and other people.'),
(7844894, 'A dictionary-based sentiment classification method considering subject-predicate relation', 'In order to achieve enhanced credibility of social networking services such as twitter, it is necessary to (1) identify the topic and to (2) check, if the majority of the tweets having the same topic show the same opinion. Therefore, it is indicated to improve the accuracy for analyzing the caller''s emotional expression of the "emotional polarity classification", which is used for opinion classification. For this reason, a semantic orientation acquisition technique is proposed, which integrates "another part-of-speech based semantic orientation dictionary" and a subject predicate relationship considered semantic orientation dictionary of phrases (semantic orientation table). As a feature of the proposed method, a semantic orientation of an adjective or predicate due to its greatest impact on identification semantic orientation of each tweet or document is determined. In addition, the dictionary is created by using tweets. Usual methods have problems with the opinion classification (90 % of the tweets are judged negative), but the proposed method has a more correct to negative judge rate of 60%. An integrated semantic orientation dictionary of phrases is used to improve precision of the classification.'),
(7847046, 'Using Multi-features and Ensemble Learning Method for Imbalanced Malware Classification', 'The ever-growing malware threats in the cyber spacecalls for techniques that are more effective than widely deployedsignature-based detection system. To counter large volumes ofmalware variants, machine learning techniques have been appliedfor automated malware classification. Despite these efforts haveachieved a certain success, the accuracy and efficiency stillremained inadequate to meet demand, especially when thesemachine learning techniques are used in the situation of multipleclass classification and imbalanced training data. Against thisbackdrop, the goal of this paper is to build a malware classificationsystem that could be used to improve the above mentionedsituation. Our system is based on multiple categories of staticfeatures and ensemble learning method. Compared to sometraditional systems it has the following advantages. Firstly, withmultiple categories of features, our system could classify malwareto their corresponding family effectively and efficiently and at thesame time avoid the influence of evasion in certain extent. Ourmethod don''t need any unpacking process and extract featuresfrom the bytes file and disassembled asm file directly. Secondly, the system employed two efficient ensemble learning models, namely XGBoost and ExtraTreeClassifer, and also combinedstacking method to construct the final classifier. Finally, weexperimented our system with the dataset provided by Microsofthosted in Kaggle for malware classification competition, andthe final results show that our method could classify malwareto their family effectively and efficiently with the accuracy of0.9972 in training set and logloss of 0.00395 in testing set. Ourwork not only offer insights into how to use multiple features forclassification, but also shed light on how to develop a scalabletechniques for automated malware classification in practice.'),
(7859473, 'Learning Roadway Surface Disruption Patterns Using the Bag of Words Representation', 'Accurately classifying roadway surface disruptions (RSDs) plays a crucial role to enhance quality transportation and road safety. To this end, smartphones are becoming an ad hoc tool to collect road data, while the user is at the steering wheel. In this paper, for the first time, sensed data are represented with a novel technique inspired in the bag of words representation. New results suggest that segments of accelerometer readings play a key role to characterize different classes of events, boosting classification performance. A novel data collection process was conducted in real-life environments, where the smartphones were freely placed at five user-surveyed locations, within a fleet of cars and trucks. To the best of our knowledge, this is the largest and most heterogenous data set for RSDs, and we make it publicly available. We approach the problem of identifying RSDs as one of supervised learning, where we contrast representative classifiers, most of them not previously reported. We exhaustively evaluated the performance of all classifiers in six data sets, most of them resembling actual data sets used in similar projects. We found that in all cases, the best classifier outperforms the best results reported so far. The proposed methodology was extensively evaluated through a sensitivity analysis to determine the relevance of the parameters. Experimental results reveal that the representation technique boosts considerably the classification performance when compared with the state of the art solutions, reducing in one order of magnitude the false-positives/negatives rate and surpassing the classification accuracy for about 10% in a multiclass data set.'),
(7872910, 'Appliance recognition system for ILM using AGILASx - Dataset of common appliances in the Philippines', 'This study presents the development of a system which can automatically recognize home appliances based on a dataset of electric consumption profiles. The authors report the creation of AGILASx, a dataset of 50 common home appliances and devices in the Philippines. The dataset is populated with 100 appliance signatures in .XML format acquired using plug-based sensors. Each appliance signature consists of the following electric characteristics: real power (W), apparent power (VA), reactive power (var), RMS current (A), RMS voltage (V) and Power Factor (PF). A machine learning approach was utilized for the recognition experiment following a set of test protocols - intersession and unseen instances. The baseline recognition algorithm used was the k-Nearest Neighbor (k-NN) for both test protocols and accuracy levels were collected over three different acquisition frequencies. Using results of the confusion matrices, best results were observed at acquisition frequency of 10?1 Hz for intersession (99%) and unseen instance (99%) test protocols. Lastly, to integrate the dataset and the recognition algorithm, a web application was developed adapting a Web-of-Things architecture to present a smart of recognized appliances and their corresponding consumption.'),
(7877010, 'TrueNorth Ecosystem for Brain-Inspired Computing: Scalable Systems, Software, and Applications', 'This paper describes the hardware and software ecosystem encompassing the brain-inspired TrueNorth processor - a 70mW reconfigurable silicon chip with 1 million neurons, 256 million synapses, and 4096 parallel and distributed neural cores. For systems, we present a scale-out system loosely coupling 16 single-chip boards and a scale-up system tightly integrating 16 chips in a 4 ? 4 configuration by exploiting TrueNorth''s native tiling. For software, we present an end-to-end ecosystem consisting of a simulator, a programming language, an integrated programming environment, a library of algorithms and applications, firmware, tools for deep learning, a teaching curriculum, and cloud enablement. For the scale-up systems we summarize our approach to physical placement of neural network, to reduce intra- and inter-chip network traffic. The ecosystem is in use at over 30 universities and government/corporate labs. Our platform is a substrate for a spectrum of applications from mobile and embedded computing to cloud and supercomputers.'),
(7877282, 'Ontology-driven root-cause analytics for user-reported symptoms in managed IT systems', 'Enterprise users of IT services seek real-time contextual insights during system-failure scenarios in both cloud-provisioned and legacy management systems. Current IT management systems mostly provide front-office automation support, such as ticket categorization and scheduling, using a generalized set of troubleshooting instructions. Therefore, in this paper, we propose an IT management system that provides real-time insights on user-perceived failures (e.g., "Why is application not responding?") expressed in natural language texts. We achieve this through an underpinning of a knowledge graph that helps in discovering possible topology patterns comprising multiple interdependent systems for a specific purpose. Based on the detected list of topology patterns, the proposed system composes multiple debugging workflows to generate accurate operational insights. The user interactions are "system agnostic" in nature and do not depend on the knowledge of the underlying system topology. This significantly augments the self-assist scenarios of end-users and front-office agents, before they engage with IT support teams. We demonstrate our proposed approach, as a cloud application with a natural language interface, using an experimental setup involving a standard ticket management system.'),
(7877755, 'Real-time performance evaluation and stability testing of RasPBX for VoWiFi', 'VoWiFi or deployment of VoIP over wireless medium can facilitate campus-wide provisioning of IP-based voice service. Determining the performance and capacity limits is essential for proper dimensioning of the service in an enterprise. This paper analyzes the real-time performance of an economical RasPBX based Asterisk system for VoWiFi service in terms of voice capacity and quality. The call blocking probability serves as the voice capacity metric and the voice quality is assessed from network packet losses. Prediction of subscriber capacity from these parameters using Erlang-B model to ensure a scalable system deployment has also been outlined in this work.'),
(7880051, 'Review of personalized language learning systems', 'This study reviews published scientific literature on personalized language learning systems. The focus is threefold: 1) present a review and categorization framework that can be used to analyze and classify personalized language learning systems, 2) analyze recent work in personalized language learning systems and organize them under the proposed framework, 3) identify current trends, challenges and open research questions in the field. Our review led us to propose a review and classification scheme with two dimensions each with a few sub-elements: language learning dimension and technical dimension. The reviewed articles indicate that recent language personalization systems increasingly introduce Artificial Intelligence and focus on cognitive-based personalization. Findings also suggest that language personalization systems may improve by incorporating more complex adaptive learner''s model and more complex contextual language learning tasks.'),
(7880282, 'An approach to support education of data mining algorithms', 'The aim of this article is to describe the design, implementation and evaluation of the educational application to support learning of data mining algorithms. The role of the application is to help students to better understand the algorithms such as Naive Bayes classifier, decision trees and association rules. The application also includes a test area that allows students to generate and solve different types of tasks on one hand side and teachers provide an effective way to test students without the need for creating custom tests on the other side. Presented application was evaluated from the perspective of students and teachers of the subject Knowledge Discovery, in order to verify the functionality and usability of the application in the real teaching process.'),
(7880341, 'A new object proposal generation method for object detection in RGB-D data', 'This paper proposes a modified selective search method that generates object proposals on RGB-D data in indoor scenes. The proposed method first applies color flattening to generate monotonous color variations in RGB image data. Then, from the color-flattened image and depth map data, cost function-based segment grouping and depth segmentation are applied to produce desirable segmentation results. Segment grouping using cost function on image data computes dissimilarities in color, texture, and size between two adjacent regions with pre-learned weights. Depth segmentation uses the height difference of grid cells in the binned depth grid map. The final set of object proposal regions extracted from the RGB image and depth map data is organized by considering the overlapping between two data modalities. Finally, the extracted set of object proposal regions is fed into AlexNet or VGG-16, both of which are widely used for object classification, to evaluate our method on object detection and classification tasks. The proposed segment-based method can precisely detect meaningful object regions using a smaller number of proposals than other methods. Further, its detection and classification performance are better than those of previous methods.'),
(7880493, 'Applying Visual Analytics on Traditional Data Mining Process: Quick Prototype, Simple Expertise Transformation, and Better Interpretation', 'Due to a lack of experience, business might not be confident about the completeness of their proposed data mining (DM) project objectives at early stage. Besides, business domain expertise usually shrinks when delivered to data analysts. This expertise ought to contribute more throughout whole project. In addition, the outcome from DM project might fail to transform into actionable advice as the interpretation for the outcome is hard to understand and, as a result, unconvincing to apply in real. To fill the above three gaps, Visual Analytics (VA) tools are applied in different stages to optimize traditional data analytics process. In my practice, VA tools have offered both an easy access to generate quick insights for evaluating project objective''s viability, and a bidirectional channel between data analysts and stakeholders to break the background barrier. Consequently, more applicable outcomes and better client satisfaction are gained.'),
(7881336, 'A Collaborative Privacy-Preserving Deep Learning System in Distributed Mobile Environment', 'In the last couple years, deep learning gained great popularity in health and medical science. For analyzing personal health data, privacy of patients and their data is one of the biggest concerns. Traditional methods have the possibility of leaking data because of transferring raw data and storing all data in centralized houseware. Therefore, we proposed a collaborative privacy-preserving learning system based on deep neural network, which does not share local raw data. The system is implemented on an XMPP server and several mobile devices. In the experiments, reconstructed rate is proposed to evaluate the performance of distributed system compared with centralized training. The rate is over 90% in different scenarios. Furthermore, the network traffic while collaborative learning is also measured.'),
(7881719, 'IRIS: A goal-oriented big data analytics framework on Spark for better Business decisions', 'Big data analytics is the hottest new practice in Business Analytics today. However, recent industrial surveys find that big data analytics may fail to meet business expectations because of lack of business context and lack of expertise to connect the dots, inaccurate scope and batch-oriented Hadoop system. In this paper, we present IRIS - a goal-oriented big data analytics framework using Spark for better business decisions, which consists of a conceptual model which connects a business side and a big data side providing context information around the data, a claim-based evaluation method which enables to focus the most effective solutions, a process on how to use IRIS framework and an assistant tool using Spark which is a real-time big data analytics platform. In this framework, problems against business goals of the current process and solutions for the future process are explicitly hypothesized in the conceptual model and validated on real big data using big queries or big data analytics. As an empirical study, a shipment decision process is used to show how IRIS can support better business decisions in terms of comprehensive understanding both on business and data analytics, high priority and fast decisions.'),
(7885075, 'A Novel Semisupervised Active-Learning Algorithm for Hyperspectral Image Classification', 'Less training samples are a challenging problem in hyperspectral image classification. Active learning and semisupervised learning are two promising techniques to address the problem. Active learning solves the problem by improving the quality of the training samples, while semisupervised learning solves the problem by increasing the quantity of the training samples. However, they pay too much attention to the discriminative information in the unlabeled data, leading to information bias to train supervised models, and much more effort to label samples. Therefore, a method to discover representativeness and discriminativeness by semisupervised active learning is proposed. It takes advantages of both active learning and semisupervised learning. The representativeness and discriminativeness are discovered with a labeling process based on a supervised clustering technique and classification results. Specifically, the supervised clustering results can discover important structural information in the unlabeled data, and the classification results are also highly confidential in the active-learning process. With these clustering results and classification results, we can assign pseudolabels to the unlabeled data. Meanwhile, the unlabeled samples that cannot be assigned with pseudolabels with high confidence at each iteration are regarded as candidates in active learning. The methodology is validated on four hyperspectral data sets. Significant improvements in classification accuracy are achieved by the proposed method with respect to the state-of-the-art methods.');

-- --------------------------------------------------------

--
-- Table structure for table `rating`
--

CREATE TABLE IF NOT EXISTS `rating` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UserID` int(11) DEFAULT NULL,
  `PaperID` int(11) DEFAULT NULL,
  `rating` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=35 ;

--
-- Dumping data for table `rating`
--

INSERT INTO `rating` (`ID`, `UserID`, `PaperID`, `rating`) VALUES
(1, 1, 7885075, 4),
(2, 1, 7880051, 5),
(3, 1, 7881336, 3),
(4, 1, 7880282, 5),
(5, 2, 7880341, 1),
(6, 2, 7881719, 5),
(7, 2, 7880493, 4),
(8, 3, 7881336, 5),
(9, 3, 7880282, 5),
(10, 4, 7814581, 3),
(11, 4, 7312541, 2),
(12, 4, 5715225, 5),
(13, 4, 5955202, 1),
(14, 3, 7877010, 0),
(15, 3, 7877755, 1),
(16, 5, 7877282, 5),
(17, 5, 7872910, 2),
(18, 5, 7574269, 3),
(19, 5, 7839233, 5),
(20, 5, 7859473, 0),
(21, 6, 7847046, 1),
(22, 6, 7844894, 1),
(23, 6, 7844785, 2),
(24, 6, 7828429, 0),
(25, 6, 7816636, 5),
(26, 7, 6825032, 3),
(27, 7, 7377291, 4),
(28, 7, 7768306, 5),
(29, 7, 7730387, 3),
(30, 1, 7730364, 5),
(31, 9, 7482764, 4),
(32, 9, 7388330, 3),
(33, 9, 7375453, 0),
(34, 9, 7358548, 3);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `firstName` varchar(100) DEFAULT NULL,
  `lastName` varchar(100) DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `password` varchar(200) DEFAULT NULL,
  `keywords` varchar(500) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=8 ;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`ID`, `firstName`, `lastName`, `username`, `password`, `keywords`) VALUES
(1, 'John', '', 'john', '123', 'Machine Learning , Artifial Intelligence , Data Mining , Regression'),
(2, 'Aemmy', '', 'aemmy', '123', 'Data Mining , Data Visualization , Machine Learning , Artifial Intelligence , data mining, machine learning'),
(3, 'Segar', '', 'segar', '123', 'Clothing , Genetic algorithms , Artificial neural networks'),
(4, 'Nick', '', 'nick', '123', 'Data visualization , Mobile communication , Real-time systems , Servers'),
(5, 'Zerry', '', 'zerry', '123', 'Natural languages , Machine learning algorithms , Engines , Classification algorithms , Computer science'),
(6, 'Kamat', '', 'kamat', '123', 'Mobile communication,Cloud computing,Edge computing,Mobile computing,Delays,Batteries'),
(7, 'Ansu', '', 'ansu', '123', 'Microwave sensing, Agriculture, Food products');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
